Grade-A-FHIR/Childhood-Obesity-master/Final Project/Final Application/Application/patient-facing-app/fgh/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^questionnaire/', include('questionnaire.urls')),
    url(r'^fhir/StructureDefinition/questionnaire-lowRangeImage', views.low_range_image),
    url(r'^fhir/StructureDefinition/questionnaire-highRangeImage', views.high_range_image),
] + static(settings.IMAGE_URL, document_root="./images/")

Grade-A-FHIR/Childhood-Obesity-master/Final Project/Final Application/Application/patient-facing-app/questionnaire/urls.py
from django.conf.urls import url
from . import views

app_name = "questionnaire"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^respond/(?P<form_id>[-\w]+)/$', views.respond, name='respond'),
    url(r'^respond_hh/', views.respond_hh, name='respond_hh'),
    url(r'^respond_wic/', views.respond_wic, name='respond_wic'),
    url(r'^respond_food/', views.respond_food, name='respond_food'),
    url(r'^respond_status/', views.respond_status, name='respond_status'),
    url(r'^about/', views.about, name='about'),
    url(r'^messages/', views.messages, name='messages'),
    url(r'^recommendations/', views.recommendations, name='recommendations'),
    url(r'^history/', views.history, name='history'),
    url(r'^response-details/(?P<responseid>[0-9a-f]*)/$', views.details, name='details')
]

Grade-A-FHIR/Childhood-Obesity-master/Final Project/Final Application/Application/patient-facing-app/questionnaire/models.py
from django.db import models

# Create your models here.

Grade-A-FHIR/Childhood-Obesity-master/Final Project/Final Application/Application/patient-facing-app/questionnaire/views.py
import json
import urllib2

import pytz as pytz

from functools import wraps

#import requests
from django.utils import timezone
from django.utils.decorators import available_attrs
from django.core.urlresolvers import reverse

from django.shortcuts import render,redirect
from django.template import RequestContext

from fhirclient.models import patient, questionnaire, questionnaireresponse, communication, practitioner

from datetime import datetime

import utils


def require_valid_user(view_func, invalid_user_message=None):
    if invalid_user_message is None:
        invalid_user_message = "The user you've selected appears to be invalid. \
         Please return to <a href='/questionnaire/'>the index</a> and select a different user."
    @wraps(view_func, assigned=available_attrs(view_func))
    def _wrapped(request, *args, **kwargs):
        if request.COOKIES.get('userId') is not None:
            try:
                (patientId, serverId) = get_login_info(request)
                smart = utils.getFhirClient(serverId)
                patient.Patient.read(patientId, smart.server)
            except Exception:
                context = { 'error_text' : invalid_user_message }
                return render(request, 'error.html', context)
            return view_func(request, *args, **kwargs)
        else:
            return redirect("questionnaire.views.index")
    return _wrapped

def get_login_info(request):
    patientId = request.COOKIES.get('userId')
    serverId = utils.resolveServerId(patientId,request.COOKIES.get('serverId'))
    return (patientId, serverId)


def index(request):
    context = {'patientGroups': utils.getPatientMap()}
    return render(request, 'index.html', context)

@require_valid_user
def respond(request, form_id, goal = None):
    (patientId, serverId) = get_login_info(request)
    smart = utils.getFhirClient(serverId)

    childRecord = patient.Patient.read(patientId, smart.server)

    try:
        qMap = utils.getQuestionnaireMap()
        form = questionnaire.Questionnaire.read(qMap[serverId][form_id], smart.server)

        jsonResponse = []
        if request.method == 'POST':
            jsonResponse = {"group": {"linkId": "root"}, "resourceType": "QuestionnaireResponse",
                            "questionnaire": {"reference": "Questionnaire/"+form.id}, "status": "completed",
                            "subject": {"reference": "Patient/"+childRecord.id},
                            "author": {"reference": "Patient/"+childRecord.id},
                            "authored": datetime.today().isoformat()}
            if form.group.question is not None:
                jsonResponse["group"]["question"] = []
                for question in form.group.question:
                    type = {"text":"valueString", "boolean":"valueBoolean", "integer":"valueInteger"}[question.type]
                    questionJson = {"linkId": question.linkId, "answer": [{type: request.POST.get(question.linkId, default=0)}]}
                    jsonResponse["group"]["question"].append(questionJson)
            if form.group.group is not None:
                jsonResponse["group"]["group"] = []
                for group in form.group.group:
                    groupJson = {"linkId": group.linkId, "question":[]}
                    for question in group.question:
                        type = {"text":"valueString", "boolean":"valueBoolean", "integer":"valueInteger"}[question.type]
                        questionJson = {"linkId": question.linkId, "answer": [{type: request.POST.get(question.linkId, default=0)}]}
                        groupJson["question"].append(questionJson)
                    jsonResponse["group"]["group"].append(groupJson)

            print json.dumps(jsonResponse)
            smart.server.post_json('QuestionnaireResponse', jsonResponse)
            return redirect("/questionnaire/")

        context = {}
        context['patientName'] = smart.human_name(childRecord.name[0])
        context['questionnaire'] = form.group
        context['form_id'] = form_id
        context['json'] = jsonResponse
        if goal is not None:
            context['goalQuestionnaire'] = goal[0]
            context['goalResponse'] = goal[1]

        #return JsonResponse(jsonResponse)
        return render(request, 'questionnaire.html', context)

    except:
    #except requests.exceptions.HTTPError as error:
        # print(error)
        # print(error.response.text)
        context = {'error_text' : "Couldn't connect to the FHIR server or FHIR server has been reset. \
         Please contact <a href='mailto:asmiley3@gatech.edu'>the team</a> and ask them to investigate."}
        return render(request, 'error.html', context)

@require_valid_user
def respond_hh(request):
    (patientId, serverId) = get_login_info(request)
    smart = utils.getFhirClient(serverId)

    childRecord = patient.Patient.read(patientId, smart.server)
    age = (datetime.now().date() - childRecord.birthDate.date).days / 365.24

    if age < 13:
        return respond(request, utils.CHILD_FORM)
    else:
        return respond(request, utils.TEEN_FORM)

@require_valid_user
def respond_wic(request):
    return respond(request, utils.WIC_FORM)

@require_valid_user
def respond_food(request):
    return respond(request, utils.FOOD_FORM)

@require_valid_user
def respond_status(request):
    (patientId, serverId) = get_login_info(request)
    smart = utils.getFhirClient(serverId)
    qMap = utils.getQuestionnaireMap()
    timezone.activate(pytz.timezone("US/Eastern"))
    (patientId, serverId) = get_login_info(request)
    smart = utils.getFhirClient(serverId)

    try:
        search = questionnaireresponse.QuestionnaireResponse.where(struct={"patient": patientId,
            "questionnaire":qMap[serverId][utils.GOAL_FORM],"_sort:desc": "authored", "_count": "30"})
        responses = search.perform_resources(smart.server)
        if len(responses)>0:
            goal_response = responses[0]
            goal_questionnaire = questionnaire.Questionnaire.read(qMap[serverId][utils.GOAL_FORM], smart.server)
            return respond(request, utils.STATUS_FORM, goal=(goal_questionnaire,goal_response))
        else:
            context = {'error_text' : "No goals have been set yet.  Try again soon!"}
            return render(request, 'error.html', context)
    except Exception:
        context = RequestContext(request)
        context['error_text'] = "There was an error retrieving the text goal information."
        return render(request, 'error.html', context)


@require_valid_user
def messages(request):
    timezone.activate(pytz.timezone("US/Eastern"))
    (patientId, serverId) = get_login_info(request)
    smart = utils.getFhirClient(serverId)
    childRecord = patient.Patient.read(patientId, smart.server)

    search = communication.Communication.where(struct={"recipient": "Patient/"+patientId})
    # This is a hack to work around a bug in the SMART on FHIR server.
    # The bug should go away when they finish their switch to a HAPI FHIR-based implementation.
    if serverId == utils.SMART:
        search = communication.Communication.where(struct={"recipient": patientId})
    messages = search.perform_resources(smart.server)
    if len(messages) > 0:
        context = RequestContext(request)

        def timestamp_key(entry):
            return entry.sent.date
        context['patientName'] = smart.human_name(childRecord.name[0])
        context['messages'] = sorted(messages, key=timestamp_key, reverse=True)
        return render(request, 'messages.html',
                                  context_instance=context)
    else:
        context = {}
        context['patientName'] = smart.human_name(childRecord.name[0])
        context['error_text'] = "No messages yet.  Check back soon!"
        return render(request, 'error.html', context)


@require_valid_user
def recommendations(request):
    timezone.activate(pytz.timezone("US/Eastern"))
    (patientId, serverId) = get_login_info(request)
    smart = utils.getFhirClient(serverId)
    childRecord = patient.Patient.read(patientId, smart.server)
    url = 'https://engine.gradeafhir.pw/api/recs?patient='+ patientId
    print(url)
    req = urllib2.Request(url, headers={'User-Agent' : "Magic Browser"})     
    serialized_data = urllib2.urlopen(req).read()
 
    recs = json.loads(serialized_data)
    recommendations = recs['entry']
    
    
    if len(recommendations) > 0:
        context = {}
            
        context['patientName'] = smart.human_name(childRecord.name[0])
        context['recommendations'] = recommendations
        return render(request, 'recommendations.html', context)
    else:
        context = {}
        context['patientName'] = smart.human_name(childRecord.name[0])
        context['error_text'] = "No Recommendations yet.  Check back soon!"
        return render(request, 'error.html', context)

@require_valid_user
def history(request):
    timezone.activate(pytz.timezone("US/Eastern"))
    (patientId, serverId) = get_login_info(request)
    smart = utils.getFhirClient(serverId)
    childRecord = patient.Patient.read(patientId, smart.server)

    search = questionnaireresponse.QuestionnaireResponse.where(struct={"patient": patientId, "_sort:desc": "authored", "_count": "30"})
    responses = search.perform_resources(smart.server)
    if len(responses) > 0:
        response_groups = {}
        for response in responses:
            ref = response.questionnaire.reference.split('/')[1]
            if ref in response_groups:
                response_groups[ref]['responses'].append(response)
            else:
                response_groups[ref] = {'questionnaire':utils.resolveFhirReference(response.questionnaire, server=smart.server), 'responses':[response]}

        context = {}
        context['pastResponses'] = response_groups
        context['patientName'] = smart.human_name(childRecord.name[0])
        return render(request, 'history.html', context)
    else:

Grade-A-FHIR/Childhood-Obesity-master/Final Project/Final Application/Application/patient-facing-app/questionnaire/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}
<h2>Disclaimer: This is a prototype that was created as a class project. If you've somehow found your way here and don't know anything about the project, please don't put any actual personal information into the forms. If you have concerns about your health, consult with a medical professional.</h2>

<a href="#patients">Usage Information for Patients</a><br>
<a href="#testing">Testing and Usage Information for the Prototype</a><br>
<a href="#background">Development Background</a>

<hr>
<h2 id="patients">Usage Information for Patients</h2>
<p><b>The following information is presented as if to a real user of the program.</b></p>
<h3>What is this site?</h3>
<p>This site contains a short list of questions intended to be filled out with information about a child or teenager. Your responses will be made available to your doctor, and you may receive followup information on resources available in your community.</p>
<h3>Why is this important?</h3>
<p>Children and teenagers who are overweight or obese are at risk for serious health problems, both immediately and later in life. They're also growing quickly, and it's not a good idea for them to try to diet or lose weight without help from a medical professional. This app is designed to help identify what may put children or teenagers at risk, and to help doctors to provide the right guidance so each individual can live a healthier life.</p>
<h3>How do I use this page?</h3>
<p>You start by using the login information that you've been given. <b>(Not yet implemented. In reality, testers need to choose a patient from the list or one that's available on the test servers.)</b> Then, you can go to the  <a href="/questionnaire/respond/">Questionnaire</a>  page to fill in your information. It will give you a short list of questions and possible answers. Choose the bubble that you feel is most accurate for each question and then click <b>Submit</b> at the bottom of the page.</p>
<h3>What if I'm not sure how to answer?</h3>
<p>It's okay if your answers aren't perfect; just do as well as you can. Please don't change answers to try to avoid sounding bad. Everything here is confidential and is meant to allow doctors to help. They can do that best when they know what's really going on.<b> (Reminder: This is a prototype. This system is not yet actually secured. Please don't submit personal information.)</b></p>
<h3>What kind of resources are available?</h3>
<p>We hope for the system to provide information and referrals related to both healthy eating and an active lifestyle. This may include information about local farmer's markets, cooking classes, and activities like dance classes or athletic teams.</p>
<p>In some cases, the doctor may need to run tests before deciding what steps are best for a particular patient.</p>
<h3>Can I see my past responses?</h3>
<p>Yes! These are available in the <a href="/questionnaire/history/">History</a> tab.</p>
<h3>How do I get messages from my care provider?</h3>
<p>Go to the <a href="/questionnaire/messages/">Messages</a>  tab. Any messages the system has for you will be there, and will be clearly marked with a date and time of arrival.</p>
<h3>What if I change my mind about answering the questions?</h3>
<p>If you haven't finished filling out the questionnaire and you decide you'd like to stop, simply leave the site without submitting your information. Nothing will be sent to the server unless you choose to hit <b>Submit</b>.</p>

<hr>
<h2 id="testing">Prototype Testing and Usage</h2>
<h3>How can I test this prototype?</h3>
<p>The main page of the webapp has a list of potential patients you can pretend to be while using the application. You can also select a FHIR server and provide the name of a patient yourself.</p>
<p>Once you're acting as a patient, you can go to the <a href="/questionnaire/respond/">Questionnaire</a>  page to see what the questionnaire looks like and to try filling it out and submitting it. You can go to the <a href="/questionnaire/history/">History</a>  page to see past submissions related to the same patient. You can also go to the <a href="/questionnaire/messages/">Messages</a>  page to see what messages have been sent to this patient by the care-provider.</p>
<h3>Why is there a list of patients instead of an actual login process?</h3>
<p>Proper secure handling of data with FHIR databases is a complicated issue that the community hasn't fully addressed. In our case, we still need to develop a separate system that will allow a patient to securely generate (or receive) login information that will tie the data they put into the form to their identity in the FHIR server. Since this step of the design isn't yet complete, the prototype includes several example links that allow you to view what the system would look like to different hypothetical patients.</p>
<h3>Why do some entries list only a name and others say "Parent/guardian of"?</h3>
<p>The current intention is that parents or guardians will fill out the form on behalf of young children. Teenagers, on the other hand, usually know their own habits well enough that they can best do this for themselves. There are also some differences in the questions asked, and minor adjustments to look and layout to better suit different age groups.</p>
<h3>How were these questions chosen?</h3>
<p>The list of questions, and the range of possibilities as responses, were provided to us by the CDC for the purpose of working on this project. They're the same questions that are already in use on paper questionnaires used to health professionals.</p>
<h3>What technologies were used to build this?</h3>
<p>It's a python web server using Django. All form responses are sent to a FHIR server. While there are other teams who built related projects, all communication between this app and others is managed by storing information on, and retrieving information from, the appropriate FHIR server.</p>
<h3>What FHIR server does this use?</h3>
<p>On the main page of the questionnaire, the app has a drop-down box that allows you to select either the MiHIN server or the SMART server. These are both FHIR servers, and our team provided support for both to maximize compatibility with other teams who were developing their projects on different servers.</p>
<hr>
<h2 id="background">Real Background Information</h2>

<h3>What is the purpose of the Healthy Habits Tracker?</h3>
<p>This is a prototype web application that's intended to help the CDC combat the obesity epidemic. It demonstrates that patients could fill out a simple form online that would make the information available to their doctors and to community health workers who could then contact them if needed and help to ensure that they have the resources needed to lead healthier lives.</p>

<h3>What's the next step?</h3>
<p>Now that there's a prototype system showing that this technology can work for information gathering, the plan is to extend the project through the summer of 2016. The team will continue to polish and expand its functionality, in hopes of creating a system that can be tested in the community and eventually used to improve lives.</p>
<p>The ultimate intention is to release the entire system as open source software so that it can be improved further, and perhaps used as the basis for additional programs that will help with the tracking and treatment of other health problems.</p>

<h3>Who created this project?</h3>
<p>This is a product of the Frogs' Greatest HITs team at Georgia Institute of Technology, Atlanta, GA. It's for the course CS6440 Introduction to Health Informatics during the spring term of 2016.</p>
<p>Team Members:</p>
<ul>
    <li>Wade Ashby - UI Lead</li>
    <li>Bobbie Eicher - Documentation Lead</li>
    <li>Scott Leitstein - Team Coordinator</li>
    <li>Cindy Schaller - Project Manager</li>
    <li>Dana Sheahen - Test Lead</li>
    <li>Angela Smiley - Design Architecture Lead</li>
</ul>
<img src="/static/fgh-logo-no-background.png"/>
{% endblock %}

Grade-A-FHIR/Childhood-Obesity-master/Final Project/Final Application/Application/patient-facing-app/questionnaire/templates/base.html
{% load menu %}{% generate_menu %}

{% load staticfiles %}
<!doctype html>
{# SRL: Adding Bootstrap specific coding for mobile first design#}
<html>
    <head>
        <title>{% block title %}Questionnaire{% endblock %}</title>

        <script src="{% static 'js/jquery-1.10.2.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery-ui.custom.min.js' %}"></script>
        <script src="{% static 'js/modernizr-custom-3.3.1.js' %}"></script>
        <script src="{% static 'js/fgh-cdc.js' %}"></script>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bemat-admin.css' %}" />
        <link rel="stylesheet" type="text/css" href="{%  static 'css/fgh-cdc-style-rev.css' %}" />

        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block headextra %}{% endblock %}
    </head>

    <body class="container-fluid">
        <div id="page-wrapper">
            <div id="left-content" data-toggle="open" data-default="open" data-size="" class="SidebarOpen">
                <header class="header-container">
					<div class="header-wrapper">
						<div id="header-brand">
							<div class="logo padding-left-2">
								<span class="logo-image">HH</span>
								<span class="logo-text">Healthy Habits Tracker</span>
							</div>
						</div>
					</div>
				</header>
                <div id="sidebar-wrapper" class="ps-container ps-active-y">
                    {% with menu=menus.main %}{% include "menu.html" %}{% endwith %}
                </div>
            </div>
            <div id="right-content" class="SidebarOpen">
                <header class="header-container">
                    <div class="header-wrapper">
                        <div id="header-toolbar">
                            <ul class="toolbar toolbar-left">
                                <li>
                                    <a id="sidebar-toggle" data-state="open" href="#" class="SidebarOpen">
                                        <i class="material-icons">menu</i>
                                    </a>
                                </li>
                            </ul>
                            <ul class="toolbar toolbar-right">
								<li id="user-profile" class="dropdown open">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
										<div class="avatar">
{#											<img src="img/avatar/avatar_square_blue.png" class="img-circle img-responsive">#}
										</div>
										<div class="user">
											<span class="username">
                                                {%  if patientName %}
                                                    {{ patientName }}
                                                {%  else %}
                                                    Please select a patient
                                                {%  endif %}
                                            </span>&nbsp;&nbsp;<i class="fa fa-user fa-lg"></i>
										</div>

									</a>
{#									<ul class="dropdown-menu dropdown-menu-right" style="min-width: 180px;">#}
{#										<li class="materialRipple-dark materialRipple-btn animation-delay-pos6"><a href="#"><i class="material-icons">person</i> <span data-i18n="userinfo.profile">Profile</span></a><div class="materialRipple-md-ripple-container"></div></li>#}
{#										<li class="materialRipple-dark materialRipple-btn animation-delay-pos5"><a href="#"><i class="material-icons">settings</i> <span data-i18n="userinfo.settings">Settings</span></a><div class="materialRipple-md-ripple-container"></div></li>#}
{#										<li class="divider-horizontal materialRipple-dark materialRipple-btn animation-delay-pos4"><div class="materialRipple-md-ripple-container"></div></li>#}
{#										<li class="materialRipple-dark materialRipple-btn animation-delay-pos3"><a href="#"><i class="material-icons">lock</i> <span data-i18n="userinfo.lock">Lock</span></a><div class="materialRipple-md-ripple-container"></div></li>#}
{#										<li class="divider-horizontal materialRipple-dark materialRipple-btn animation-delay-pos2"><div class="materialRipple-md-ripple-container"></div></li>#}
{#										<li class="materialRipple-dark materialRipple-btn animation-delay-pos1"><a href="#"><i class="material-icons">exit_to_app</i> <span data-i18n="userinfo.logout">Log Out</span></a><div class="materialRipple-md-ripple-container"></div></li>#}
{#									</ul>#}
								</li><!-- /#user-profile -->
							</ul>

                        </div>
                    </div>
                </header>
                <section id="right-content-wrapper">
					<div class="right-content-outter">
						<div class="right-content-inner" style="opacity: 1;">
                            <section class="page-header alternative-header">
{#                                <ol class="breadcrumb">#}
{#                                    <li>Admin</li>#}
{#                                    <li>Dashboard</li>#}
{#                                    <li>Pages</li>#}
{#                                </ol>#}
                                <div class="page-header_title">
                                    <h1>
                                        {%  if request.path ==  "/questionnaire/" %}
                                            Home
                                        {% elif request.path ==  "/questionnaire/respond_hh/" %}
                                            Healthy Habits Questionnaire
                                        {% elif request.path ==  "/questionnaire/respond_wic/" %}
                                            WIC Questionnaire
                                        {% elif request.path ==  "/questionnaire/respond_food/" %}
                                            Food Insecurity Questionnaire
                                        {% elif request.path ==  "/questionnaire/respond_status/" %}
                                            Healthy Habit Goal Status Questionnaire
                                        {% elif request.path ==  "/questionnaire/messages/" %}
                                            Messages
                                        {% elif request.path ==  "/questionnaire/history/" %}
                                            Questionnaire History
                                        {% elif request.path ==  "/questionnaire/recommendations/" %}
                                            Recommendations
                                        {% elif request.path ==  "/questionnaire/about/" %}
                                            About
                                        {% elif "response-details" in request.path %}
                                            Response Details
                                        {%  else %}
                                            {{ request.path }}
                                        {%  endif %}
                                        <span class="page-header_subtitle"></span>
                                    </h1>
                                </div>
                            </section>

                            <section class="page-content">
                                <div class="row">
                                    <div class="col-lg-12">

                                            <div class="panel panel-default">

                                                <div class="panel-body" >

                                                    {% block content %}  {% endblock %}
                                                </div>
                                            </div>


                                    </div>
                                </div>
                            </section>



                        </div>
                    </div>
                </section>
            </div>
        </div>
    </body>
</html>

Grade-A-FHIR/Childhood-Obesity-master/Final Project/Final Application/Application/patient-facing-app/questionnaire/templates/bootstrap-navbar.html
{% for item in menu %}
{% if item.separator %}<li class="divider-vertical"></li>{% endif %}
<li class="{% if item.selected %} active{% endif %}{% if item.children %} dropdown{% endif %}" id="top-menu-{{ item.slug }}">
    {% if item.children %}
    <a href="#" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown">{% if item.icon %}<i class="icon-{{ item.icon }} icon-white"></i>&nbsp;{% endif %}{{ item.title }}&nbsp;<b class="caret"></b></a>
    <ul class="dropdown-menu">
        {% for child in item.children %}<li{% if child.selected %} class="active"{% endif %}><a href="{{ child.url }}">{{ child.title }}</a></li>{% endfor %}
    </ul>
    {% else %}
    <a href="{{ item.url }}">{% if item.icon %}<i class="icon-{{ item.icon }} icon-white"></i>&nbsp;{% endif %}{{ item.title }}</a>
    {% endif %}
</li>
{% endfor %}

Grade-A-FHIR/Childhood-Obesity-master/Final Project/Final Application/Application/patient-facing-app/questionnaire/templates/doc_base.html
{% load staticfiles %}
<!doctype html>
{# SRL: Adding Bootstrap specific coding for mobile first design#}
<html>
    <head>
        <title>{% block title %}Questionnaire{% endblock %}</title>
        <script src="https://code.jquery.com/jquery-1.12.1.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="http://bootswatch.com/cosmo/bootstrap.min.css" />
		<link rel="stylesheet" type="text/css" href="{%  static 'css/fgh-cdc-style.css' %}" />


        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block headextra %}{% endblock %}
    </head>

    <body>
        <div class="main" style="padding:0 10pt">{% block content %}</div>
        {% endblock %}
    </body>
</html>

Grade-A-FHIR/Childhood-Obesity-master/Final Project/Final Application/Application/patient-facing-app/questionnaire/templates/error.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}
{{ error_text|safe }}
{% endblock %}

Grade-A-FHIR/Childhood-Obesity-master/Final Project/Final Application/Application/patient-facing-app/questionnaire/templates/history.html
{% extends "base.html" %}

{% load fhir_formatting %}

{% block content %}
    <style>
        span.label {
            font-weight: bold;
        }
    </style>

    <ul class="nav nav-tabs">
      {% for qid, responseGroup in pastResponses.items %}
      <li {% if forloop.first %}class="active"{% endif %}><a data-toggle="tab" href="#{{ qid }}">{{ responseGroup.questionnaire.group.title|tab_title }}</a></li>
      {% endfor %}
    </ul>
    <div class="tab-content">
      {% for qid, responseGroup in pastResponses.items %}
      <div class="tab-pane fade in {% if forloop.first %}active{% endif %}" id="{{ qid }}">
        <h3>{{ responseGroup.questionnaire.group.title }}</h3>
        <div>Your past responses:</div>
        {% for response in responseGroup.responses %}
            <div class="response">
                <span class="label">Submitted:</span>
                <a href="{% url 'questionnaire:details' response.id %}">{%  if response.authored %}{{ response.authored.date }}{% else %}{{ response.meta.lastUpdated.date }}{% endif %}</a>
            </div>
        {% endfor %}
      </div>
      {% endfor %}
    </div>
{% endblock %}